apiVersion: v2
name: pythonflaskapp
version: 0.0.1
description: A Simple Helm Chart for Python Flask Application
type: application
keywords:
  - python
  - flask
# sources:
#   - https://github.com/mathesh-me/helm-python-flask-app
maintainers:
  - name: rymsaidi
    email: rym.saidi@esprit.tn
    url: https://github.com/rymsaidi/Python-flask-app
icon: https://helm.sh/img/helm.svg
appVersion: 0.0.1